language: c

matrix:
  include:
    - os: linux
      env: TARGET="linux"
    - os: linux
      env: TARGET="windows"
    - os: osx
      env: TARGET="mac"
    - os: linux
      env: TARGET="arm_linux"

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: "build/deploy/*"
  skip_cleanup: true

branches:
  only:
    - master

install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sudo apt-get install curl; fi

script:
  - sh build.sh

