name: Make_All
on: push
jobs:
  Make_All:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push a new tag
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.21
          packages: >
            zip
            binutils
            make
            curl
            git
      - name: Build all
        run: chmod ugo+x pack.sh build.sh; ./pack.sh update; ./build.sh
        shell: alpine.sh {0}
        
      - name: Generate Tag
        id: generate_tag
        run: |
          TAG_PREFIX="v0.1"
          TAG_SUFFIX="$(git rev-parse HEAD)"
          NEW_TAG="${TAG_PREFIX}-${TAG_SUFFIX}"
          echo "Generated tag: $NEW_TAG"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
          # export the variable for next step
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - run: echo "pushing artifact"
        id: push_artifact
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.generate_tag.outputs.NEW_TAG}}
          files: |
             build/deploy/*
